networks:
  default:
    external:
      name : roboshop
services:
  mongodb:
    image: mongodb:1.0.0
    container_name : mongodb
    # networks : 
    # - roboshop

  catalogue:
    image: catalogue:1.0.0
    container_name: catalogue
    # networks:
    # - roboshop
  web:
    image: web:1.0.0
    container_name: web
    ports:
      - "80:80"
    depends_on:
    - catalogue
    # networks:
    # - roboshop
